---
language: python
python: "2.7"

env:
  - IMAGE=fedora TAG=24
  - IMAGE=fedora TAG=23
  - IMAGE=fedora TAG=22

dist: trusty
sudo: required

cache: pip

before_install:
  - sudo apt-get update
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y apt-transport-https ca-certificates
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - echo 'deb https://apt.dockerproject.org/repo ubuntu-trusty main' | sudo tee /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confdef" -y docker-engine
  - docker version
  - docker pull $IMAGE:$TAG
  - docker run --privileged=true --name test -di $IMAGE:$TAG /bin/bash
  - |
    if [ ${TAG} = "22" ]; then
      docker exec test yum install -y python2 sudo
    else
      docker exec test dnf install -y python2 python2-dnf sudo
    fi

install:
  - pip install ansible
  - ansible --version
  - printf '[defaults]\nroles_path=../\ncallback_whitelist=profile_tasks' | tee ansible.cfg
  - pip install ansible-lint

script:
  - ansible-playbook -i localhost, --syntax-check tests/test.yml
  - ansible-lint tests/test.yml
  - ansible-playbook -i test, tests/test.yml

notifications:
  email: false
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

