---

- name: package mock is installed
  yum:
    pkg="mock{{ '-' + mock_version if mock_version is defined else '' }}"
    state="{{ 'present' if mock_version is defined else 'latest' }}"

- name: user {{ mock_user }} is present and in mock group
  user:
    name={{ mock_user }}
    groups=mock
    append=yes

- name: create mock repository {{ mock_config }}
  command:
    /usr/bin/mock -r {{ mock_config }} --init
    creates=/var/lib/mock/{{ mock_config }}/root
  register: mock_init_result
  failed_when: "'ERROR' in mock_init_result.stderr"
  become: yes
  become_user: '{{ mock_user }}'
  when: mock_config != ''
